### ISSUE TITLE
SDK-PHP:php-actors actors reference

### ISSUE THREAD

**Issue by RcXu** [dapr-cn/docs#246]
https://crowdin.com/translate/cndocsdapr/16084/en-zhcn?filter=basic&value=0
https://crowdin.com/translate/cndocsdapr/16086/en-zhcn?filter=basic&value=0

**Comment by RcXu** [comment]
review了一部分内容，但是有一些内容历史过于久远，做了简单调整需要交叉review

**Comment by skyao** [comment]
done
