### ISSUE TITLE
hugo-头部标记 linkTitle翻译

### ISSUE THREAD

**Issue by JadynWong** [dapr-cn/docs#28]
[Hugo 头部标记](https://github.com/dapr-cn/docs/blob/main/TranslationNotes.md#hugo-%E5%A4%B4%E9%83%A8%E6%A0%87%E8%AE%B0)
![image](https://user-images.githubusercontent.com/13699353/110272242-addb7f80-8004-11eb-9a6d-8f58e47167b6.png)

我觉得linkTitle还是应该翻译，除非为特点术语，或cli 命令
目前效果看起来比较奇怪

**Comment by newbe36524** [comment]
原来我们一直以为 link title 是影响链接地址路径的。
但是现在看来好像只会影响翻译的内容。

随后我会尝试确认一下。
如果只是影响左侧的翻译内容，不会影响文件之间的链接的话。那么确实应该翻译。否则就不能翻译了。

**Comment by JadynWong** [comment]
![image](https://user-images.githubusercontent.com/13699353/110309967-f151e000-803c-11eb-88db-4ae6954fdfc6.png)
![image](https://user-images.githubusercontent.com/13699353/110310975-201c8600-803e-11eb-870f-b0618216b07b.png)


按现有翻译，部分翻译了linkTitle的内容来看应该是不影响连接路径的，只是作为超连接标题

[https://gohugo.io/content-management/front-matter/](https://gohugo.io/content-management/front-matter/)

linkTitle
used for creating links to content; if set, Hugo defaults to using the linktitle before the title. Hugo can also order lists of content by linktitle.

**Comment by newbe36524** [comment]
非常感谢你提供的有效信息！
我将修改翻译指导内容。
