### ISSUE TITLE
Add contributors

### ISSUE THREAD

**Issue by newbe36524** [dapr-cn/docs#30]

**Comment by newbe36524** [comment]
@all-contributors please add @newbe36524 for idea, translation

**Comment by newbe36524** [comment]
@all-contributors please add @newbe36524 for idea, translation

**Comment by newbe36524** [comment]
@all-contributors please add @skyao for idea, translation

**Comment by newbe36524** [comment]
@all-contributors please add @LLLLimbo for  translation

**Comment by newbe36524** [comment]
@all-contributors please add @abserari for translation

**Comment by newbe36524** [comment]
@all-contributors please add @sheng-jie for translation

**Comment by newbe36524** [comment]
@all-contributors please add @danvic712 for translation

**Comment by newbe36524** [comment]
@all-contributors please add @JadynWong for translation

**Comment by newbe36524** [comment]
@all-contributors please add @oudi for translation

**Comment by newbe36524** [comment]
@all-contributors please add @ZhangX-Byte for translation

**Comment by newbe36524** [comment]
@all-contributors please add @siegrainwong for translation

**Comment by newbe36524** [comment]
@all-contributors please add @lifejoyforpy for translation

**Comment by newbe36524** [comment]
@all-contributors please add @MarkLux for translation

**Comment by newbe36524** [comment]
@all-contributors please add @charleszhn for translation

**Comment by newbe36524** [comment]
@all-contributors please add @TomorJM for translation

**Comment by newbe36524** [comment]
@all-contributors please add @weihanli for translation

**Comment by newbe36524** [comment]
@all-contributors please add @herowk for translation

**Comment by newbe36524** [comment]
@all-contributors please add @ipfans for translation

**Comment by newbe36524** [comment]
@all-contributors please add @itoktsnhc for translation

**Comment by newbe36524** [comment]
@all-contributors please add @Stitch-Zhang for translation

**Comment by newbe36524** [comment]
@all-contributors please add @stulzq for translation

**Comment by newbe36524** [comment]
@all-contributors please add @zcong1993 for translation

**Comment by newbe36524** [comment]
@all-contributors please add @Z4t4r for translation

**Comment by lifejoyforpy** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by newbe36524** [comment]
@all-contributors please add @jerrold0607 for translation

**Comment by lifejoyforpy** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
