### ISSUE TITLE
官方站 1.1 版本文档 fix https://github.com/dapr/docs/pull/1485

### ISSUE THREAD

**Issue by zcong1993** [dapr-cn/docs#66]
https://github.com/dapr/docs/pull/1485

不知道怎么提交 pr 到中文站

**Comment by newbe36524** [comment]
非常感谢你的留言。
中文站点由于维护人员有限，我们只会进行定期更新。
只要你将最新的内容提交到英文主站点，我们进行同步时就会自动更新。
