### ISSUE TITLE
关于代码段翻译的特殊处理说明

### ISSUE THREAD

**Issue by newbe36524** [dapr-cn/docs#67]
结论：
对于代码段，不应该对其进行翻译。应该使用 "Hide String" 功能对其进行隐藏。操作如下图：
![image](https://user-images.githubusercontent.com/7685462/119251484-5bf4cf80-bbd9-11eb-807a-7f5c6ba13a72.png)

该规则可以扩展应用到其他任何不需要翻译的内容上。例如：

1. 单行代码段
![image](https://user-images.githubusercontent.com/7685462/119251563-bd1ca300-bbd9-11eb-9a40-a6d29c068071.png)
2. hugo metadata 头部内容
![image](https://user-images.githubusercontent.com/7685462/119251500-6adb8200-bbd9-11eb-9b40-30906adba549.png)
3. hugo 代码块
![image](https://user-images.githubusercontent.com/7685462/119251518-85156000-bbd9-11eb-9bec-e460d93347c2.png)

注意，混编在文本中的代码段不受此规则约束。

原因：

例如，存在以下代码段

```bash
aaaa
bbbb
cccc
```

如果直接将内容直接拷贝为翻译内容，则该词条会进入TM。如果代码段内容发生了变化，变为：

```bash
aaaa
bbbb
cccc
dddd
```

当使用 TM 进行翻译时，由于 crowdin 的识别问题，可能会导致该段出现内容重复，格式错乱的情况。
故而以上内容若在 TM 中不存在，则不会出现错误的替换。

**Comment by Stitch-Zhang** [comment]
Hide String这个功能在我这边没找到，菜单点开没有这个选项

![image](https://user-images.githubusercontent.com/61350804/119260385-22d25480-bc05-11eb-8fc2-140ea2a06d3c.png)

**Comment by Stitch-Zhang** [comment]
😶经过与客服沟通后，了解到作为译者是没有权限使用"Hide String" 

![image](https://user-images.githubusercontent.com/61350804/119260849-4e563e80-bc07-11eb-8b64-bedf94ec5434.png)

**Comment by newbe36524** [comment]
> 😶经过与客服沟通后，了解到作为译者是没有权限使用"Hide String"
> 
> ![image](https://user-images.githubusercontent.com/61350804/119260849-4e563e80-bc07-11eb-8b64-bedf94ec5434.png)

谢谢你的反馈，那看来只能让管理员一个个点了
