### ISSUE TITLE
Update new GA criteria and rename GA to Stable in CN docs

### ISSUE THREAD

**Issue by willtsai** [dapr-cn/docs#80]
Hello,

Please reference the changes documented in https://github.com/dapr/docs/issues/1879 to make the same changes in the Dapr CN docs. Below are the PRs you can reference for the changes that were made to accommodate the new [`Stable`](https://v1-5.docs.dapr.io/operations/components/certification-lifecycle/#stable) lable and criteria that have replaced the previously named `GA` as of Dapr release v1.5

Files needing update:
```
daprdocs/content/en/operations/components/certification-lifecycle.md
daprdocs/content/en/operations/support/support-versioning.md
daprdocs/content/en/reference/*
```

PRs for reference:
- https://github.com/dapr/docs/pull/1880
- https://github.com/dapr/docs/pull/1904

**Comment by newbe36524** [comment]
yeah, will do
