### ISSUE TITLE
有部分地方需要处理翻译

### ISSUE THREAD

**Issue by whuanle** [dapr-cn/docs#81]
https://docs.dapr.io/zh-hans/getting-started/install-dapr-selfhost/
![image](https://user-images.githubusercontent.com/2189761/140596961-a5b04e82-fbb1-4ca5-9f6b-9dd98121d3dc.png)

https://docs.dapr.io/zh-hans/getting-started/get-started-api/
![image](https://user-images.githubusercontent.com/2189761/140596969-4c8d9a46-a642-4556-ab95-2000c3739730.png)

**Comment by whuanle** [comment]
https://docs.dapr.io/zh-hans/developing-applications/building-blocks/service-invocation/service-invocation-overview/
![image](https://user-images.githubusercontent.com/2189761/140597149-83451088-835b-4b57-b367-904b37cc2287.png)

**Comment by newbe36524** [comment]
您可以通过首页的 readme 了解如何提交相应的贡献内容。期待您的更新。

**Comment by newbe36524** [comment]
see more https://daprcn-docs-team.newbe.pro/docs/intro
